version : '2.32.4'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=database
      - MONGO_INITDB_ROOT_USERNAME=admin

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINPASSWORD=database
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - serviceName: mongodb
        condition: service_healthy

